name: Main workflow
on: [push]
jobs:
  build-src:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ 'src/', 'samples/EsiaNet8Sample/', 'samples/EsiaSample' ]
    name: Build ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - run: dotnet build ${{ matrix.project }}
