name: NuGet publish workflow
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package into NuGet
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            6.x
            8.x
            9.x
      - name: Pack
        run: dotnet pack src -c release -o bld
      - name: Rename
        run: find bld/ -type f -name "*.nupkg" -exec mv {} bld/out.nupkg \;
      - name: Push
        run: dotnet nuget push bld/out.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
