name: NuGet publish workflow
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package into NuGet
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build Esia
        uses: ./.github/actions/publish-project
        with:
          project-name: Esia
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
      - name: Build Esia.BouncyCastle
        uses: ./.github/actions/publish-project
        with:
          project-name: Esia.BouncyCastle
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Build Esia.CryptoPro
        uses: ./.github/actions/publish-project
        with:
          project-name: Esia.CryptoPro
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
